meter_data:
  ip: "10.15.1.2"
  # ip: "8.8.8.8"
  port: 502
  meter_type: "Phoenix Generic"

auth:
  name: "admin"
  register: 16403
  pin: 100

write_registers:
  - name: power_factor_L1
    address: 32816
    value: 10
  - name: power_factor_L2
    address: 32818
    value: 20
  - name: power_factor_L3
    address: 32820
    value: 30

read_registers:
  - name: voltage_L1_N
    address: 32774
  - name: voltage_L2_N
    address: 32776
  - name: voltage_L3_N
    address: 32778
  - name: current_L1_N
    address: 32782
  - name: current_L2_N
    address: 32784
  - name: current_L3_N
    address: 32786
  - name: active_power_L1_N
    address: 32798
  - name: active_power_L2_N
    address: 32800
  - name: active_power_L3_N
    address: 32802
  - name: reactive_power_L1_N
    address: 32804
  - name: reactive_power_L2_N
    address: 32806
  - name: reactive_power_L3_N
    address: 32808
  - name: power_factor_L1
    address: 32816
  - name: power_factor_L2
    address: 32818
  - name: power_factor_L3
    address: 32820
  - name: grid_frequency
    address: 32780
  - name: total_current
    address: 32825
  - name: total_active_power
    address: 32790
  - name: total_apparent_power
    address: 32794
  - name: total_reactive_power
    address: 32792

debug:
  mgw_generic: "off"
  statemachine_modbus: "info"
  statemachine_read: "info"